# Generated by Django 4.1.7 on 2023-03-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_paid_amount_alter_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.IntegerField(),
        ),
    ]
